<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jalan_1</name>
   <tag></tag>
   <elementGuidId>5b86c1de-3a5f-496a-a191-09cb56130457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deskripsi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='deskripsi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>78a7c914-f963-407c-b709-660a01bd35ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8ad69603-c07f-41c7-a0ae-386d10cde882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>9aaff073-6f8c-43d1-afa6-e1f664e8ef48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1f834a22-b183-46ea-8512-4856ebd08bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Jalan Ikan Hiu 33</value>
      <webElementGuid>a4c0974d-f28f-4a2b-b8d1-b3fbb217df24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jalan </value>
      <webElementGuid>c6ab35ba-74a5-4078-8170-68fbd8614553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deskripsi&quot;)</value>
      <webElementGuid>9f9783e3-6e70-48c8-8ba5-9f888222a710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='deskripsi']</value>
      <webElementGuid>0831e01e-6b85-42ae-ba12-4116319a9153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div[3]/textarea</value>
      <webElementGuid>9f388b6a-13f9-4616-afaa-c3882f0532bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat*'])[1]/following::textarea[1]</value>
      <webElementGuid>cd95a3e2-6344-4879-bf22-b50b830eadaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota*'])[1]/following::textarea[1]</value>
      <webElementGuid>15f3b6d0-e797-4d7c-af2b-3c0c37b5eb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.Handphone*'])[1]/preceding::textarea[1]</value>
      <webElementGuid>0423f0d8-bb1f-4915-bf3f-cfb4f2eb1982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>5d8b9ce5-0bf5-4613-82cd-7c5092c6df5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d46c758c-227e-4564-ac11-2bb3c3515f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'deskripsi' and @placeholder = 'Contoh: Jalan Ikan Hiu 33' and (text() = 'Jalan ' or . = 'Jalan ')]</value>
      <webElementGuid>7cef1c53-db74-488f-9537-8538700973a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
