<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Ikan Paus 2</name>
   <tag></tag>
   <elementGuidId>7324b868-03d1-4fe7-bfd5-4016830fbcb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deskripsi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='deskripsi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>941a4dd9-dc7e-47f9-991a-43f6da904467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4322af40-8587-496f-a31b-b7d8ac91d1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>8c567c03-d8ad-4719-bdc3-af864ef945aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>412caf61-9094-4199-be3c-dd3670681816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Jalan Ikan Hiu 33</value>
      <webElementGuid>9177612d-0d37-4bdc-a553-b66c09319bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ikan Paus 2 </value>
      <webElementGuid>262d9dae-b4a4-4dde-abaa-487f63d79aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deskripsi&quot;)</value>
      <webElementGuid>049f1e82-be06-4e56-ace9-aaee1aa1f952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f048c8f4-e5dd-4fd3-8ae0-a14e0dde5d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c8eb418a-9aac-4b39-bd88-cb27adf38a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>b0093630-747a-40da-94d3-d03f7232b1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fb592c52-2d70-41b6-a00f-63fabcbf754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Jalan Ikan Hiu 33</value>
      <webElementGuid>b647fbe3-50a9-40bd-b3f8-6d22053ca703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ikan Paus 2</value>
      <webElementGuid>d2ccc914-03a2-45df-9697-8c575a7d3a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deskripsi&quot;)</value>
      <webElementGuid>b1079baf-5c9b-4745-b4bb-9db71b4a60e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='deskripsi']</value>
      <webElementGuid>1c12fc1d-7998-44c7-8c40-b4ffe36143b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div[3]/textarea</value>
      <webElementGuid>650346e1-5ac6-4428-a918-a50824a725a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat*'])[1]/following::textarea[1]</value>
      <webElementGuid>ce7540f2-09fd-44db-b8c9-69cff4723017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota*'])[1]/following::textarea[1]</value>
      <webElementGuid>414ed991-1b2e-47b0-ae46-4fd0bc759eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.Handphone*'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8c0b02d4-2990-40fa-85fa-ad08e08412b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b9d690e7-59a5-4881-a33b-e6d963322774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a1d6788b-347f-44d5-9764-86cf6f474946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'deskripsi' and @placeholder = 'Contoh: Jalan Ikan Hiu 33' and (text() = 'Ikan Paus 2 ' or . = 'Ikan Paus 2 ')]</value>
      <webElementGuid>b771894c-5e6a-4605-9f6e-73fac10fcec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ikan Paus 2']/parent::*</value>
      <webElementGuid>3517c468-133e-4aae-a2be-77aa25007917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'deskripsi' and @placeholder = 'Contoh: Jalan Ikan Hiu 33' and (text() = 'Ikan Paus 2' or . = 'Ikan Paus 2')]</value>
      <webElementGuid>7919e3cb-8f5f-460b-bd60-2829674d3b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
